import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        primary: '#2E6FF2',
        second: '#5C8EF2',
        third: '#F3F5FA',
        border: '#D9DBE0',
        'code-bg': '#282C34',
        black: 'rgb(0 0 0 / <alpha-value>)',
        white: 'rgb(255 255 255 / <alpha-value>)',
        text: 'rgb(var(--color--text) / <alpha-value>)',
        fore: 'rgb(var(--color--fore) / <alpha-value>)',
        back: 'rgb(var(--color--back) / <alpha-value>)',
        back_layout: 'rgb(var(--color--back_layout) / <alpha-value>)',
        gutter: 'rgb(var(--color--gutter) / <alpha-value>)',
        guide: 'rgb(var(--color--guide) / <alpha-value>)',
        accent: 'rgb(var(--color--accent) / <alpha-value>)',
        cyan: 'rgb(var(--color--cyan) / <alpha-value>)',
        blue: 'rgb(var(--color--blue) / <alpha-value>)',
        purple: 'rgb(var(--color--purple) / <alpha-value>)',
        green: 'rgb(var(--color--green) / <alpha-value>)',
        rose: 'rgb(var(--color--rose) / <alpha-value>)',
        orange: 'rgb(var(--color--orange) / <alpha-value>)',
        red: 'rgb(var(--color--red) / <alpha-value>)',
        gold: 'rgb(var(--color--gold) / <alpha-value>)',
        transparent: 'transparent',
      },
      typography: ({ theme }: { theme: any }) => ({
        custom: {
          css: {
            '--tw-prose-body': theme('colors.gray[800]'),
            '--tw-prose-headings': theme('colors.gray[900]'),
            '--tw-prose-lead': theme('colors.gray[700]'),
            '--tw-prose-links': theme('colors.gray[900]'),
            '--tw-prose-bold': theme('colors.gray[900]'),
            '--tw-prose-counters': theme('colors.gray[600]'),
            '--tw-prose-bullets': theme('colors.gray[400]'),
            '--tw-prose-hr': theme('colors.gray[500]'),
            '--tw-prose-quotes': theme('colors.gray[900]'),
            '--tw-prose-quote-borders': theme('colors.gray[300]'),
            '--tw-prose-captions': theme('colors.gray[700]'),
            '--tw-prose-code': theme('colors.gray[900]'),
            '--tw-prose-pre-code': theme('colors.gray[100]'),
            '--tw-prose-pre-bg': theme('colors.code-bg'),
            '--tw-prose-th-borders': theme('colors.gray[500]'),
            '--tw-prose-td-borders': theme('colors.gray[400]'),
            '--tw-prose-invert-body': theme('colors.gray[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.gray[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.gray[400]'),
            '--tw-prose-invert-bullets': theme('colors.gray[600]'),
            '--tw-prose-invert-hr': theme('colors.gray[700]'),
            '--tw-prose-invert-quotes': theme('colors.gray[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.gray[700]'),
            '--tw-prose-invert-captions': theme('colors.gray[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.gray[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.gray[600]'),
            '--tw-prose-invert-td-borders': theme('colors.gray[700]'),
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
export default config;
